# Yukawa Coupling Paths via QGF Fusion

This notebook computes categorical Yukawa couplings in the QGF framework.  
Coupling strength is modeled using fusion paths between composite objects in the product category \( SU(3)_3 \times SU(2)_2 \times U(1)_q \), weighted by quantum dimensions.

In [1]:
import pandas as pd
import numpy as np

In [4]:
# Load selected fusion rules from data
fusion_df = pd.read_csv("../data/C_SM_Fusion_Rules_SU3_3_SU2_2_U1.csv")
fusion_df.head()

                  a                 b                         Result
0  ((1,0), 1/2, q1)  ((0,1), 1/2, q2)          ((1,1), 0 ⊕ 1, q1+q2)
1  ((1,0), 1/2, q1)  ((1,0), 1/2, q2)  ((2,0) ⊕ (0,1), 0 ⊕ 1, q1+q2)
2    ((1,1), 1, q1)  ((0,1), 1/2, q2)    ((1,2) ⊕ (2,0), 1/2, q1+q2)
3  ((0,1), 1/2, q1)  ((0,1), 1/2, q2)  ((0,2) ⊕ (1,0), 0 ⊕ 1, q1+q2)
4    ((2,0), 0, q1)  ((0,1), 1/2, q2)    ((2,1) ⊕ (1,0), 1/2, q1+q2)

In [5]:
# Path weight estimator

quantum_dims = {
    "(1,0)": 3,
    "(0,1)": 3,
    "(1,1)": 8,
    "(2,0)": 6,
    "1/2": 1.4142,
    "1": 1,
    "0": 1
}

def estimate_path_weight(objects):
    weight = 1.0
    for obj in objects:
        key = str(obj).strip()
        if key in quantum_dims:
            weight *= quantum_dims[key]
    return 1 / weight if weight != 0 else 0

In [6]:
# Example: Evaluate path weights for result objects

fusion_df["Weight"] = fusion_df["Result"].apply(
    lambda result: estimate_path_weight(result.replace("⊕", ",").replace("(", "").replace(")", "").split(","))
)

fusion_df[["a", "b", "Result", "Weight"]]

,a,b,Result,Weight
0,"((1,0), 1/2, q1)","((0,1), 1/2, q2)","((1,1), 0 ⊕ 1, q1+q2)",1.000000
1,"((1,0), 1/2, q1)","((1,0), 1/2, q2)","((2,0) ⊕ (0,1), 0 ⊕ 1, q1+q2)",1.000000
2,"((1,1), 1, q1)","((0,1), 1/2, q2)","((1,2) ⊕ (2,0), 1/2, q1+q2)",0.707114
3,"((0,1), 1/2, q1)","((0,1), 1/2, q2)","((0,2) ⊕ (1,0), 0 ⊕ 1, q1+q2)",1.000000
4,"((2,0), 0, q1)","((0,1), 1/2, q2)","((2,1) ⊕ (1,0), 1/2, q1+q2)",0.707114
5,"((1,1), 1/2, q1)","((1,1), 1/2, q2)","((0,0) ⊕ (1,1) ⊕ (2,2), 0 ⊕ 1, q1+q2)",1.000000

In [7]:
# Sort by weight to highlight most suppressed couplings
fusion_df_sorted = fusion_df.sort_values(by="Weight", ascending=True)
fusion_df_sorted.head()

                  a                 b                         Result    Weight
2    ((1,1), 1, q1)  ((0,1), 1/2, q2)    ((1,2) ⊕ (2,0), 1/2, q1+q2)  0.707114
4    ((2,0), 0, q1)  ((0,1), 1/2, q2)    ((2,1) ⊕ (1,0), 1/2, q1+q2)  0.707114
1  ((1,0), 1/2, q1)  ((1,0), 1/2, q2)  ((2,0) ⊕ (0,1), 0 ⊕ 1, q1+q2)  1.000000
0  ((1,0), 1/2, q1)  ((0,1), 1/2, q2)          ((1,1), 0 ⊕ 1, q1+q2)  1.000000
3  ((0,1), 1/2, q1)  ((0,1), 1/2, q2)  ((0,2) ⊕ (1,0), 0 ⊕ 1, q1+q2)  1.000000

The resulting weights reflect the entropic or categorical suppression of Yukawa-like couplings.  
Light fermions emerge from higher-dimensional or multi-object fusion paths, consistent with QGF-based flavor hierarchies.